name: latest-builds

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: 16
        distribution: 'adopt'
    - uses: gradle/wrapper-validation-action@v1
    - name: Build 
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: artifacts
        path: build/libs