name: Recent release
on:
  release:
     types:
       - published
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Wrapper
        run: chmod +x ./gradlew
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Upload to GitHub
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'build/libs/*.jar;LICENSE'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
